# Generated by Django 4.2.26 on 2025-11-29 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("importer", "0005_dataimportsession_update_records"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierProductImportSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "data_file",
                    models.FileField(
                        help_text="CSV file containing supplier product data",
                        upload_to="supplier_imports",
                        verbose_name="CSV File",
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        help_text="Name of the supplier for these products",
                        max_length=255,
                        verbose_name="Supplier Name",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "parts_created",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Parts Created"
                    ),
                ),
                (
                    "supplier_parts_created",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Supplier Parts Created"
                    ),
                ),
                (
                    "errors",
                    models.JSONField(blank=True, default=list, verbose_name="Errors"),
                ),
                ("import_log", models.TextField(blank=True, verbose_name="Import Log")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Product Import",
                "verbose_name_plural": "Supplier Product Imports",
                "ordering": ["-timestamp"],
            },
        ),
    ]
