# Generated by Django 5.2.8 on 2025-12-15 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Change supplier_name CharField to supplier ForeignKey."""

    dependencies = [
        ("company", "0076_alter_company_image"),
        ("importer", "0006_supplierproductimportsession"),
    ]

    operations = [
        # First delete all existing rows (if any) - table is new so should be empty
        migrations.RunSQL(
            "DELETE FROM importer_supplierproductimportsession;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name="supplierproductimportsession",
            name="supplier_name",
        ),
        migrations.AddField(
            model_name="supplierproductimportsession",
            name="supplier",
            field=models.ForeignKey(
                help_text="Supplier for these products",
                limit_choices_to={"is_supplier": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="company.company",
                verbose_name="Supplier",
            ),
        ),
    ]
