# Generated by Django 5.2.8 on 2025-11-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_manager", "0002_allow_null_seller_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceprocessinglog",
            name="action",
            field=models.CharField(
                choices=[
                    ("UPLOAD", "Upload"),
                    ("EXTRACT", "Extract"),
                    ("MATCH", "Match Part"),
                    ("PO_CREATE", "Purchase Order Created"),
                    ("STOCK_CREATE", "Stock Created"),
                    ("STOCK_ERROR", "Stock Error"),
                    ("ERROR", "Error"),
                ],
                max_length=20,
            ),
        ),
    ]
