# Generated by Django 5.2.8 on 2025-11-30 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice_manager", "0003_alter_invoiceprocessinglog_action"),
        ("order", "0114_purchaseorderextraline_project_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Purchase Order created from this invoice",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="order.purchaseorder",
            ),
        ),
    ]
