# Generated by Django 5.2.8 on 2025-12-15 21:37

import amazon_sales.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0114_purchaseorderextraline_project_code_and_more"),
        ("part", "0143_alter_part_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmazonSalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text='Optional name for this report (e.g., "July 2024")',
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "csv_file",
                    models.FileField(
                        help_text="Amazon sales report CSV file",
                        upload_to=amazon_sales.models.amazon_report_upload_path,
                        verbose_name="CSV File",
                    ),
                ),
                (
                    "date_from",
                    models.DateField(
                        blank=True,
                        help_text="Start date of the report period",
                        null=True,
                        verbose_name="Date From",
                    ),
                ),
                (
                    "date_to",
                    models.DateField(
                        blank=True,
                        help_text="End date of the report period",
                        null=True,
                        verbose_name="Date To",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (10, "Uploaded"),
                            (20, "Parsed"),
                            (30, "Matching ASINs"),
                            (40, "Ready to Process"),
                            (50, "Processing"),
                            (60, "Completed"),
                            (90, "Error"),
                        ],
                        default=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Processing notes and logs",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "total_lines",
                    models.IntegerField(default=0, verbose_name="Total Lines"),
                ),
                (
                    "matched_lines",
                    models.IntegerField(default=0, verbose_name="Matched Lines"),
                ),
                (
                    "unmatched_lines",
                    models.IntegerField(default=0, verbose_name="Unmatched Lines"),
                ),
                (
                    "orders_created",
                    models.IntegerField(default=0, verbose_name="Orders Created"),
                ),
            ],
            options={
                "verbose_name": "Amazon Sales Report",
                "verbose_name_plural": "Amazon Sales Reports",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="AmazonSalesReportLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_number",
                    models.IntegerField(
                        help_text="Row number in CSV", verbose_name="Row"
                    ),
                ),
                (
                    "shipment_date",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Shipment Date"
                    ),
                ),
                (
                    "merchant_sku",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Merchant SKU"
                    ),
                ),
                (
                    "fnsku",
                    models.CharField(blank=True, max_length=20, verbose_name="FNSKU"),
                ),
                (
                    "asin",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, verbose_name="ASIN"
                    ),
                ),
                (
                    "fulfillment_center",
                    models.CharField(blank=True, max_length=10, verbose_name="FC"),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="Quantity")),
                (
                    "amazon_order_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=30,
                        verbose_name="Amazon Order Id",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GBP", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "product_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Product Amount",
                    ),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Shipping Amount",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=50, verbose_name="State"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Postal Code"
                    ),
                ),
                (
                    "match_status",
                    models.IntegerField(
                        choices=[
                            (0, "Pending"),
                            (1, "Auto-matched"),
                            (2, "Manually matched"),
                            (3, "Not Found"),
                            (4, "No ASIN"),
                        ],
                        default=0,
                        verbose_name="Match Status",
                    ),
                ),
                (
                    "matched_part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amazon_report_lines",
                        to="part.part",
                        verbose_name="Matched Part",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="amazon_sales.amazonsalesreport",
                        verbose_name="Report",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amazon_report_lines",
                        to="order.salesorder",
                        verbose_name="Sales Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Line",
                "verbose_name_plural": "Report Lines",
                "ordering": ["row_number"],
            },
        ),
    ]
