# Generated by Django 5.2.8 on 2025-12-17 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amazon_sales", "0001_initial"),
        ("stock", "0116_alter_stockitem_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="amazonsalesreport",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Location to allocate stock from when creating sales orders",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="stock.stocklocation",
                verbose_name="Stock Location",
            ),
        ),
    ]
